### ISSUE TITLE
スポンサー追加タスク

### ISSUE THREAD

**Issue by mapconcierge** [droneimpactchallenge/www_dichallenge_org#1]
スポンサー表記追記
* FRSKY社さま
* goldstone社さま

**Comment by mapconcierge** [comment]
現状ロゴ待ち。

**Comment by mkdrone** [comment]
![default](https://cloud.githubusercontent.com/assets/12077013/13439304/36e1da60-e030-11e5-9950-ec0ad99c3ba9.png)
![12325436_963825290363370_1923113836_n](https://cloud.githubusercontent.com/assets/12077013/13439321/554d61c2-e030-11e5-8605-9eab06febe6d.jpg)



リンク先は、
http://www.goldstones-japan.com/
http://www.frsky-rc.com/product/

**Comment by mapconcierge** [comment]
200x69 pix
![s_banner_orso_logo_s](https://cloud.githubusercontent.com/assets/416977/13442597/5fc58f98-e040-11e5-94aa-95ee27d25905.jpg)

**Comment by mapconcierge** [comment]
![s_banner_frsky_logo_s](https://cloud.githubusercontent.com/assets/416977/13442647/97fe9ac6-e040-11e5-8859-52dd2d56ae78.jpg)
![s_banner_goldstones_logo_s](https://cloud.githubusercontent.com/assets/416977/13442646/97fe8734-e040-11e5-93ee-aefdc590d4bc.jpg)

**Comment by mapconcierge** [comment]
ロゴ追加だん
https://github.com/droneimpactchallenge/www_dichallenge_org/commit/3dcafd5c503f4986720325c0e76b2622085c081f

**Comment by mapconcierge** [comment]
http://dichallenge.org/
![2016-03-02 11 47 46](https://cloud.githubusercontent.com/assets/416977/13449208/9cef8802-e06c-11e5-8d46-a36cf12bc974.png)


閉じます！
