### ISSUE TITLE
スポンサー登録

### ISSUE THREAD

**Issue by mapconcierge** [droneimpactchallenge/www_dichallenge_org#6]
スポンサー登録

Japan Drone
[ヨコ-Japan-Drone.ai.zip](https://github.com/droneimpactchallenge/www_dichallenge_org/files/158565/-Japan-Drone.ai.zip)

**Comment by mkdrone** [comment]
[規約20160304.pdf](https://github.com/droneimpactchallenge/www_dichallenge_org/files/158582/20160304.pdf)

**Comment by mapconcierge** [comment]
ロゴ追加完了
![2016-03-16 20 09 17](https://cloud.githubusercontent.com/assets/416977/13813232/097f0c62-ebb3-11e5-828f-d1255c00a8c8.png)

**Comment by mapconcierge** [comment]
規約のテキスト展開
---

ドローンインパクトチャレンジ 参加規約 Ver.1.1
第 1 条(イベントへの参加) 競技者は、ドローンインパクトチャレンジ実行委員会(以下「主催者」という)による規 則、指示に従うことを了承していただきます。
第 2 条(参加拒否) 主催者は、以下のような場合、イベントの参加申し込みを強制的に解除させていただくこ とがあります。
(1) 参加者が主催者の定める事項について虚偽の申告をされた場合、または必要な申告をさ れなかった場 合。
(2) 第三者の迷惑になるような行為または主催者の円滑な業務を妨げるような行為をされ た場合。または、 その恐れがある場合。
(3) 主催者より案内した期限内に所定の手続きをされなかった場合。
(4) 主催者が指定する参加方法をお守りいただけなかった場合。
(5) 参加者が振込による入金方法を選択し振込期限までに参加代金を振り込みいただけな かった場合。
(6) お申し込みをされたにもかかわらず、決済が行われない場合。
(7) その他本参加規約に違反した場合。
第 3 条(参加料等の返金)
1. 参加者の希望により申し込まれたイベントの参加料は、イベントが開始された場合、理 由の如何を問 わず、返金はお受けできません。 2.いかなる場合においても参加料以外の費用(手数料、交通費、宿泊費、通信費、送料等) の支払いは行 いません。
第 4 条(参加者の決定) 主催者は必要に応じ、先着順、抽選等の参加方法を選択し、必要に応じ人数制限等を設け ることがあり ます。
第 5 条(申し込みの終了) 参加申込期間中であっても、主催者が予定する参加者数に達した時点で個々のイベント毎 に申し込みを 終了する場合があります。
第 6 条(禁止事項) 主催者から付与した参加権利を参加料金額を超える金額にて転売すること、またはインタ
ーネットオークション等へ出品する等の転売を試みる行為、転売を前提に参加申し込みを する行為は禁止としております。前述の行為が発覚した場合、主催者の判断で申し込みを 無効とした上で、参加料の返金並びに入場を認めないことがあります。また、既にイベン トに参加している場合には強制的に退場を命じる場合 もあります。
第 7 条(免責事項) イベントに参加して生じた直接の或いは間接的な損失、損害に対し、主催者及び協賛、ス ポンサー、イ ベント運営スタッフは一切責任を負いません。
第 8 条(契約成立)
1. 参加者は主催者指定の方法によりお申し込みいただくものとし、当該申し込みを主催者 が受領し本条 第 2 項に記載の申込完了告知の内、1つでも完了した時点をもって参加申 し込みが成立するものとしま す。
2.Web サイトにてお申し込みいただいた場合の参加申し込完了告知方法は、本サイト上で の申し込内容 を確認する画面での案内並びに申込完了に関するメールを、お申し込みの際 にご記入いただくメールア ドレスに送付することとします。
第 9 条(支払い方法) 参加申し込みに関わる料金の支払方法は主催者指定の方法の中から選択いただくものとし、 指定以外の 方法は使用できないこととします。クレジットカードでお支払いいただく場合 は主催者が指定した期日 に自動決済し、口座振込を選択された場合はお客様が主催者の定 める期限までにお支払いいただくもの とします。また、現金を選択された場合は現地にて 現金決済を行っていただくこととします。なお、場 合により支払い方法に制限を設ける場 合があることをご了承いただきます。また、原則、一度ご選択いただいた支払い方法は変 更できないこととします。
第 10 条(広報) 開催されるイベント内で主催者、新聞、テレビ、ラジオ、雑誌等が参加者を撮影、取材し、 それを報道及びその他の商業上の目的のために使用することができるものとします。 機体 に装備されたカメラによるコンテンツの著作権利所有は、ドローンインパクトチャレンジ に属するものとします。 なお、競技会の結果は、商業上の目的のために使用することができるものとします。著作 権利所有は、ドローンインパクトチャレンジに属するものとします。
第 11 条(器物の損害) 個人の所有物及び競技備品の管理は参加者の責任とし、主催者はその紛失、破損等の責任
を問いません。
第 12 条(健康管理) 参加者の健康管理は参加者の責任とし、万一事故等が発生した場合にも、主催者及びすべ てのイベント 関係者は責任を負いません。
第 13 条(イベントの変更) 気象状態の悪化及びイベント環境の不良等により日程あるいは内容が予告なしに変更され る場合があり ます。
第 14 条(代表者の責任) 申込者が代表者の場合、申込者が本規約を参加者全員に周知させ参加者全員が同意したも のとみなしま す。未成年者が参加する場合は、申込者が未成年者全員の保護者に本規約を 周知させ保護者全員が同意 したものとみなします。
第 15 条(未成年者の申し込み) 申込者が未成年者の場合、保護者の同意を必要とします。
第 16 条(その他) 上記に定める条項以外に、主催者が定める約款や規定がある場合は、それに準じた対応を 取らせていた だきます。当イベント規定については、主催者の事業内容の変更により、事 前通告なく条項を変更・追加する場合があります。
付則 本規定は 2015 年 9 月 1 日午前 0 時より実施するものとします。
