### ISSUE TITLE
国家戦略プロジェクト　秋田県仙北市　アジアカップ

### ISSUE THREAD

**Issue by mkdrone** [droneimpactchallenge/www_dichallenge_org#9]
[【１】秋田県仙北市2016_プレスリリース_ver.5.pdf](https://github.com/droneimpactchallenge/www_dichallenge_org/files/276782/2016_._ver.5.pdf)
[【２】秋田県仙北市2016_プレスリリース_ver.4.pdf](https://github.com/droneimpactchallenge/www_dichallenge_org/files/276784/2016_._ver.4.pdf)

**Comment by mapconcierge** [comment]
TOPページのNEWS欄にリンク掲載完了
